utils::globalVariables(
  c(
    "algorithm",
    "break_date",
    "break_magn",
    "cloud_mask",
    "data_type",
    "freq",
    "has_breaks",
    "has_valid_breaks_lt_med",
    "has_valid_breaks_st_med",
    "has_valid_breaks_st_trend",
    "masked_vals",
    "method",
    "original_spi",
    "spi",
    "ti",
    "type",
    "value"
  )
)
